services:
  app:
    image: iis-app:latest
    restart: always
    entrypoint: ["/bin/sh", "-c", ". /venv/bin/activate && python /app/app.py"]
    volumes:
      - .:/app:rw
    ports:
      - "5005:5000"
    tty: true
    depends_on:
      - db

  db:
    image: postgres:16.0
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "iis"
    ports:
      - "5432:5432"

  adminer:
    image: adminer:4.8.1
    restart: always
    ports:
      - "8080:8080"
