"""empty message

Revision ID: 57a8c591adef
Revises: 
Create Date: 2023-11-27 13:53:05.031172

"""
from alembic import op
import sqlalchemy as sa
import datetime


# revision identifiers, used by Alembic.
revision = '57a8c591adef'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    stop_table = op.create_table('stop',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    trafficline_table = op.create_table('trafficline',
    sa.Column('line_name', sa.String(length=10), nullable=False),
    sa.Column('starting_stop', sa.String(length=50), nullable=True),
    sa.Column('last_stop', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['last_stop'], ['stop.name'], ),
    sa.ForeignKeyConstraint(['starting_stop'], ['stop.name'], ),
    sa.PrimaryKeyConstraint('line_name')
    )
    users_table = op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    vehicles_table = op.create_table('vehicles',
    sa.Column('vin', sa.String(length=50), nullable=False),
    sa.Column('manufacturer', sa.String(length=30), nullable=True),
    sa.Column('type', sa.String(length=30), nullable=True),
    sa.Column('inspect_date', sa.Date(), nullable=True),
    sa.Column('seats', sa.Integer(), nullable=True),
    sa.Column('state', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('vin')
    )
    departures_table = op.create_table('departures',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('line_name', sa.String(length=10), nullable=False),
    sa.Column('stop_name', sa.String(length=50), nullable=False),
    sa.Column('time', sa.Time(), nullable=True),
    sa.Column('order_number', sa.Integer(), nullable=True),
    sa.Column('direction', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['line_name'], ['trafficline.line_name'], ),
    sa.ForeignKeyConstraint(['stop_name'], ['stop.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    maintenance_table = op.create_table('maintenance',
    sa.Column('ticketID', sa.Integer(), nullable=False),
    sa.Column('vin', sa.String(length=32), nullable=True),
    sa.Column('engineer', sa.Integer(), nullable=True),
    sa.Column('moderator', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('request', sa.String(length=1024), nullable=True),
    sa.Column('report', sa.String(length=1024), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['vin'], ['vehicles.vin'], ),
    sa.PrimaryKeyConstraint('ticketID')
    )
    malfunction_table = op.create_table('malfunction',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vin', sa.String(length=50), nullable=False),
    sa.Column('message', sa.String(length=100), nullable=True),
    sa.Column('created', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['vin'], ['vehicles.vin'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ride_table = op.create_table('ride',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('line_name', sa.String(length=10), nullable=True),
    sa.Column('vehicle_vin', sa.String(length=50), nullable=True),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['line_name'], ['trafficline.line_name'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_vin'], ['vehicles.vin'], ),
    sa.PrimaryKeyConstraint('id')
    )
    timestop_table = op.create_table('timestop',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_start', sa.Boolean(), nullable=True),
    sa.Column('is_end', sa.Boolean(), nullable=True),
    sa.Column('from_start', sa.Integer(), nullable=True),
    sa.Column('line_name', sa.String(length=10), nullable=False),
    sa.Column('stop_name', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['line_name'], ['trafficline.line_name'], ),
    sa.ForeignKeyConstraint(['stop_name'], ['stop.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    op.bulk_insert(
        users_table,
        [
            {'username': 'admin', 'password': '$2b$12$hT9zK6A/cyhyWJ8rD2/iS.MhWCo.ei/SLP4whj.LtE59unGzjQMW6', 'role': 'admin'},
            {'username': 'moderator', 'password': '$2b$12$1EqF7o8GltarlFpS6LgStuZrk.SAyzLqFUQcMp1m.J3yS1EGXmy2.', 'role': 'moderator'},
            {'username': 'dispatcher', 'password': '$2b$12$YMevA7orMmFkmJvt25cwP.0eeZRt.mzSmPveNBjiqV6nLR7yQ.3Ke', 'role': 'dispatcher'},
            {'username': 'engineer1', 'password': '$2b$12$7Q2RVm5kk9zK8BTVEux3Y.be4EjuFJsmGiEZPaQziFLxTbfB/l5Uy', 'role': 'engineer'},
            {'username': 'engineer2', 'password': '$2b$12$7Q2RVm5kk9zK8BTVEux3Y.be4EjuFJsmGiEZPaQziFLxTbfB/l5Uy', 'role': 'engineer'},
            {'username': 'driver1', 'password': '$2b$12$Tb8Rm8Fo6jrxZO6UTFsRbuP8sEKYRa2DAi2ggjXiX6Sh2JGOinOhe', 'role': 'driver'},
            {'username': 'driver2', 'password': '$2b$12$Tb8Rm8Fo6jrxZO6UTFsRbuP8sEKYRa2DAi2ggjXiX6Sh2JGOinOhe', 'role': 'driver'},
            {'username': 'driver3', 'password': '$2b$12$Tb8Rm8Fo6jrxZO6UTFsRbuP8sEKYRa2DAi2ggjXiX6Sh2JGOinOhe', 'role': 'driver'},
            {'username': 'driver4', 'password': '$2b$12$Tb8Rm8Fo6jrxZO6UTFsRbuP8sEKYRa2DAi2ggjXiX6Sh2JGOinOhe', 'role': 'driver'},
            {'username': 'driver5', 'password': '$2b$12$Tb8Rm8Fo6jrxZO6UTFsRbuP8sEKYRa2DAi2ggjXiX6Sh2JGOinOhe', 'role': 'driver'},
            {'username': 'driver6', 'password': '$2b$12$Tb8Rm8Fo6jrxZO6UTFsRbuP8sEKYRa2DAi2ggjXiX6Sh2JGOinOhe', 'role': 'driver'},
        ]
    )
    op.bulk_insert(
        stop_table,
        [
            {'name': 'Hlavní nádraží'},
            {'name': 'Malinovského náměstí'},
            {'name': 'Moravské náměstí'},
            {'name': 'Antonínská'},
            {'name': 'Komenského náměstí'},
            {'name': 'Sokolská'},
            {'name': 'Česká'},
            {'name': 'Kartouzská'},
            {'name': 'Šumavská'},
            {'name': 'Kounicova'},
            {'name': 'Kopečná'},
            {'name': 'Hrnčířská'},
            {'name': 'Mendlovo Náměstí'},
            {'name': 'Kuldova'},
            {'name': 'Kotlářská'},
            {'name': 'Vlhká'},
            {'name': 'Masná'},
            {'name': 'Vsetínská'},
            {'name': 'Kamenná'},
            {'name': 'Křenová'},
            {'name': 'Úvoz'},
            {'name': 'Husitská'},
            {'name': 'Náměstí Míru'},
        ]
    )
    op.bulk_insert(
        trafficline_table,
        [
            {'line_name': '1', 'starting_stop': 'Hlavní nádraží', 'last_stop': 'Šumavská'},
            {'line_name': '2', 'starting_stop': 'Moravské náměstí', 'last_stop': 'Masná'},
            {'line_name': '3', 'starting_stop': 'Komenského náměstí', 'last_stop': 'Kartouzská'},
            {'line_name': 'E46', 'starting_stop': 'Česká', 'last_stop': 'Hlavní nádraží'},
            {'line_name': 'E48', 'starting_stop': 'Masná', 'last_stop': 'Moravské náměstí'},
            {'line_name': 'E50', 'starting_stop': 'Náměstí Míru', 'last_stop': 'Moravské náměstí'},
        ]
    )
    op.bulk_insert(
        vehicles_table,
        [
            {'vin': 'v8s3bv', 'manufacturer': 'Karosa', 'type': 'k1', 'inspect_date': datetime.date(2023, 10, 8), 'seats': 30, 'state': 'in service'},
            {'vin': 'v8sbs7', 'manufacturer': 'Karosa', 'type': 'k1', 'inspect_date': datetime.date(2023, 10, 9), 'seats': 30, 'state': 'in service'},
            {'vin': 'v8sahc', 'manufacturer': 'Karosa', 'type': 'k1', 'inspect_date': datetime.date(2023, 10, 10), 'seats': 30, 'state': 'being prepared'},
            {'vin': 'vin852', 'manufacturer': 'Irisbus', 'type': 'ib2', 'inspect_date': datetime.date(2023, 9, 1), 'seats': 60, 'state': 'in service'},
            {'vin': 'vinhh1', 'manufacturer': 'Irisbus', 'type': 'ib2', 'inspect_date': datetime.date(2023, 9, 2), 'seats': 60, 'state': 'in service'},
            {'vin': 'vin871', 'manufacturer': 'Irisbus', 'type': 'ib2', 'inspect_date': datetime.date(2023, 9, 3), 'seats': 60, 'state': 'being prepared'},
            {'vin': 'vi5b6s', 'manufacturer': 'Škoda', 'type': 'tr15', 'inspect_date': datetime.date(2023, 1, 5), 'seats': 45, 'state': 'in service'},
            {'vin': 'vi591b', 'manufacturer': 'Škoda', 'type': 'tr15', 'inspect_date': datetime.date(2023, 1, 6), 'seats': 45, 'state': 'in service'},
            {'vin': 'vi5ak1', 'manufacturer': 'Škoda', 'type': 'tr15', 'inspect_date': datetime.date(2023, 1, 7), 'seats': 45, 'state': 'being prepared'},
        ]
    )
    # op.bulk_insert(
    #     maintenance_table,
    #     [
    #         {'ticketID': 1, 'vin': 'v8sbs7', 'engineer': 4, 'moderator': 2, 'date': datetime.date(2023, 1, 5), 'request': 'Change oil', 'report': 'Oil changed, oil filter changed, spark plugs changed', 'state': 'done'},
    #         {'ticketID': 2, 'vin': 'vin852', 'engineer': 5, 'moderator': 2, 'date': datetime.date(2023, 1, 23), 'request': 'Pump the wheels', 'report': 'Wheels has been pumped to the required pressure', 'state': 'done'},
    #         {'ticketID': 3, 'vin': 'vi5b6s', 'engineer': 4, 'moderator': 2, 'date': datetime.date(2023, 4, 13), 'request': 'Fix the back door', 'report': 'It was a system bug, it works again after reboot', 'state': 'done'},
    #         {'ticketID': 4, 'vin': 'vin871', 'engineer': 5, 'moderator': 2, 'date': datetime.date(2023, 5, 3), 'request': 'Front lights stopped working', 'report': 'Ordered new lights, replaced the old ones', 'state': 'done'},
    #         {'ticketID': 5, 'vin': 'v8sahc', 'engineer': 5, 'moderator': 2, 'date': datetime.date(2023, 9, 10), 'request': 'Repair air condition', 'report': 'air condition broken, must be bought new, waiting for it to deliver', 'state': 'in progress'},
    #     ]
    # )
    # op.bulk_insert(
    #     malfunction_table,
    #     [
    #         {'id': 1, 'vin': 'v8sbs7', 'message': 'Change oil', 'created': True},
    #         {'id': 2, 'vin': 'vin852', 'message': 'Pump the wheels', 'created': True},
    #         {'id': 3, 'vin': 'vi5b6s', 'message': 'Fix the back door', 'created': True},
    #         {'id': 4, 'vin': 'vin871', 'message': 'Front lights stopped working', 'created': True},
    #         {'id': 5, 'vin': 'v8sahc', 'message': 'Repair air condition', 'created': True},
    #         {'id': 6, 'vin': 'vi591b', 'message': 'Change oil', 'created': False},
    #         {'id': 7, 'vin': 'vi5ak1', 'message': 'Add cooling liquid', 'created': False},
    #     ]
    # )
    op.bulk_insert(
        ride_table,
        [
            {'line_name': '1', 'vehicle_vin': 'v8s3bv', 'driver_id': 6, 'start_time': datetime.time(6, 0, 0), 'end_time': datetime.time(10, 0, 0)},
            {'line_name': '1', 'vehicle_vin': 'vin852', 'driver_id': 7, 'start_time': datetime.time(10, 0, 0), 'end_time': datetime.time(14, 0, 0)},
            {'line_name': '1', 'vehicle_vin': 'vinhh1', 'driver_id': 8, 'start_time': datetime.time(14, 0, 0), 'end_time': datetime.time(18, 0, 0)},
            {'line_name': '2', 'vehicle_vin': 'vinhh1', 'driver_id': 8, 'start_time': datetime.time(6, 0, 0), 'end_time': datetime.time(10, 0, 0)},
            {'line_name': '2', 'vehicle_vin': 'v8s3bv', 'driver_id': 6, 'start_time': datetime.time(10, 0, 0), 'end_time': datetime.time(14, 0, 0)},
            {'line_name': '2', 'vehicle_vin': 'vin852', 'driver_id': 7, 'start_time': datetime.time(14, 0, 0), 'end_time': datetime.time(18, 0, 0)},
            {'line_name': '3', 'vehicle_vin': 'vin852', 'driver_id': 7, 'start_time': datetime.time(6, 0, 0), 'end_time': datetime.time(10, 0, 0)},
            {'line_name': '3', 'vehicle_vin': 'vinhh1', 'driver_id': 8, 'start_time': datetime.time(10, 0, 0), 'end_time': datetime.time(14, 0, 0)},
            {'line_name': '3', 'vehicle_vin': 'v8s3bv', 'driver_id': 6, 'start_time': datetime.time(14, 0, 0), 'end_time': datetime.time(18, 0, 0)},
            {'line_name': 'E46', 'vehicle_vin': 'vi5b6s', 'driver_id': 9, 'start_time': datetime.time(6, 0, 0), 'end_time': datetime.time(10, 0, 0)},
            {'line_name': 'E46', 'vehicle_vin': 'vi591b', 'driver_id': 10, 'start_time': datetime.time(10, 0, 0), 'end_time': datetime.time(14, 0, 0)},
            {'line_name': 'E46', 'vehicle_vin': 'v8sbs7', 'driver_id': 11, 'start_time': datetime.time(14, 0, 0), 'end_time': datetime.time(18, 0, 0)},
            {'line_name': 'E48', 'vehicle_vin': 'v8sbs7', 'driver_id': 11, 'start_time': datetime.time(6, 0, 0), 'end_time': datetime.time(10, 0, 0)},
            {'line_name': 'E48', 'vehicle_vin': 'vi5b6s', 'driver_id': 9, 'start_time': datetime.time(10, 0, 0), 'end_time': datetime.time(14, 0, 0)},
            {'line_name': 'E48', 'vehicle_vin': 'vi591b', 'driver_id': 10, 'start_time': datetime.time(14, 0, 0), 'end_time': datetime.time(18, 0, 0)},
            {'line_name': 'E50', 'vehicle_vin': 'vi591b', 'driver_id': 10, 'start_time': datetime.time(6, 0, 0), 'end_time': datetime.time(10, 0, 0)},
            {'line_name': 'E50', 'vehicle_vin': 'v8sbs7', 'driver_id': 11, 'start_time': datetime.time(10, 0, 0), 'end_time': datetime.time(14, 0, 0)},
            {'line_name': 'E50', 'vehicle_vin': 'vi5b6s', 'driver_id': 9, 'start_time': datetime.time(14, 0, 0), 'end_time': datetime.time(18, 0, 0)},
        ]
    )
    op.bulk_insert(
        timestop_table,
        [
            {'is_start': True, 'is_end': False, 'from_start': 0, 'line_name': '1', 'stop_name': 'Hlavní nádraží'},
            {'is_start': False, 'is_end': False, 'from_start': 1, 'line_name': '1', 'stop_name': 'Malinovského náměstí'},
            {'is_start': False, 'is_end': False, 'from_start': 2, 'line_name': '1', 'stop_name': 'Moravské náměstí'},
            {'is_start': False, 'is_end': False, 'from_start': 3, 'line_name': '1', 'stop_name': 'Antonínská'},
            {'is_start': False, 'is_end': False, 'from_start': 4, 'line_name': '1', 'stop_name': 'Komenského náměstí'},
            {'is_start': False, 'is_end': True, 'from_start': 5, 'line_name': '1', 'stop_name': 'Sokolská'},
            {'is_start': False, 'is_end': True, 'from_start': 6, 'line_name': '1', 'stop_name': 'Česká'},
            {'is_start': False, 'is_end': True, 'from_start': 7, 'line_name': '1', 'stop_name': 'Kartouzská'},
            {'is_start': False, 'is_end': True, 'from_start': 8, 'line_name': '1', 'stop_name': 'Šumavská'},

            {'is_start': True, 'is_end': False, 'from_start': 0, 'line_name': '2', 'stop_name': 'Moravské náměstí'},
            {'is_start': False, 'is_end': False, 'from_start': 1, 'line_name': '2', 'stop_name': 'Kounicova'},
            {'is_start': False, 'is_end': False, 'from_start': 2, 'line_name': '2', 'stop_name': 'Kopečná'},
            {'is_start': False, 'is_end': False, 'from_start': 3, 'line_name': '2', 'stop_name': 'Hrnčířská'},
            {'is_start': False, 'is_end': False, 'from_start': 4, 'line_name': '2', 'stop_name': 'Mendlovo Náměstí'},
            {'is_start': False, 'is_end': False, 'from_start': 5, 'line_name': '2', 'stop_name': 'Kuldova'},
            {'is_start': False, 'is_end': False, 'from_start': 6, 'line_name': '2', 'stop_name': 'Kotlářská'},
            {'is_start': False, 'is_end': False, 'from_start': 7, 'line_name': '2', 'stop_name': 'Vlhká'},
            {'is_start': False, 'is_end': True, 'from_start': 8, 'line_name': '2', 'stop_name': 'Masná'},

            {'is_start': True, 'is_end': False, 'from_start': 0, 'line_name': '3', 'stop_name': 'Komenského náměstí'},
            {'is_start': False, 'is_end': False, 'from_start': 1, 'line_name': '3', 'stop_name': 'Vsetínská'},
            {'is_start': False, 'is_end': False, 'from_start': 2, 'line_name': '3', 'stop_name': 'Kamenná'},
            {'is_start': False, 'is_end': False, 'from_start': 3, 'line_name': '3', 'stop_name': 'Křenová'},
            {'is_start': False, 'is_end': False, 'from_start': 4, 'line_name': '3', 'stop_name': 'Úvoz'},
            {'is_start': False, 'is_end': False, 'from_start': 5, 'line_name': '3', 'stop_name': 'Husitská'},
            {'is_start': False, 'is_end': False, 'from_start': 6, 'line_name': '3', 'stop_name': 'Náměstí Míru'},
            {'is_start': False, 'is_end': False, 'from_start': 7, 'line_name': '3', 'stop_name': 'Česká'},
            {'is_start': False, 'is_end': True, 'from_start': 8, 'line_name': '3', 'stop_name': 'Kartouzská'},

            {'is_start': True, 'is_end': False, 'from_start': 0, 'line_name': 'E46', 'stop_name': 'Česká'},
            {'is_start': False, 'is_end': False, 'from_start': 1, 'line_name': 'E46', 'stop_name': 'Sokolská'},
            {'is_start': False, 'is_end': False, 'from_start': 2, 'line_name': 'E46', 'stop_name': 'Komenského náměstí'},
            {'is_start': False, 'is_end': False, 'from_start': 3, 'line_name': 'E46', 'stop_name': 'Antonínská'},
            {'is_start': False, 'is_end': False, 'from_start': 4, 'line_name': 'E46', 'stop_name': 'Moravské náměstí'},
            {'is_start': False, 'is_end': False, 'from_start': 5, 'line_name': 'E46', 'stop_name': 'Malinovského náměstí'},
            {'is_start': False, 'is_end': True, 'from_start': 6, 'line_name': 'E46', 'stop_name': 'Hlavní nádraží'},

            {'is_start': True, 'is_end': False, 'from_start': 0, 'line_name': 'E48', 'stop_name': 'Masná'},
            {'is_start': False, 'is_end': False, 'from_start': 1, 'line_name': 'E48', 'stop_name': 'Vlhká'},
            {'is_start': False, 'is_end': False, 'from_start': 2, 'line_name': 'E48', 'stop_name': 'Kotlářská'},
            {'is_start': False, 'is_end': False, 'from_start': 3, 'line_name': 'E48', 'stop_name': 'Kuldova'},
            {'is_start': False, 'is_end': False, 'from_start': 4, 'line_name': 'E48', 'stop_name': 'Mendlovo Náměstí'},
            {'is_start': False, 'is_end': False, 'from_start': 5, 'line_name': 'E48', 'stop_name': 'Hrnčířská'},
            {'is_start': False, 'is_end': False, 'from_start': 6, 'line_name': 'E48', 'stop_name': 'Kopečná'},
            {'is_start': False, 'is_end': False, 'from_start': 7, 'line_name': 'E48', 'stop_name': 'Kounicova'},
            {'is_start': False, 'is_end': True, 'from_start': 8, 'line_name': 'E48', 'stop_name': 'Moravské náměstí'},

            {'is_start': True, 'is_end': False, 'from_start': 0, 'line_name': 'E50', 'stop_name': 'Náměstí Míru'},
            {'is_start': False, 'is_end': False, 'from_start': 1, 'line_name': 'E50', 'stop_name': 'Husitská'},
            {'is_start': False, 'is_end': False, 'from_start': 2, 'line_name': 'E50', 'stop_name': 'Úvoz'},
            {'is_start': False, 'is_end': False, 'from_start': 3, 'line_name': 'E50', 'stop_name': 'Křenová'},
            {'is_start': False, 'is_end': False, 'from_start': 4, 'line_name': 'E50', 'stop_name': 'Kamenná'},
            {'is_start': False, 'is_end': False, 'from_start': 5, 'line_name': 'E50', 'stop_name': 'Vsetínská'},
            {'is_start': False, 'is_end': False, 'from_start': 6, 'line_name': 'E50', 'stop_name': 'Komenského náměstí'},
            {'is_start': False, 'is_end': False, 'from_start': 7, 'line_name': 'E50', 'stop_name': 'Antonínská'},
            {'is_start': False, 'is_end': True, 'from_start': 8, 'line_name': 'E50', 'stop_name': 'Moravské náměstí'},
        ]
    )

    op.bulk_insert(
        departures_table,
        [
            {'line_name': '1', 'stop_name': 'Hlavní nádraží', 'time': datetime.time(6, 0, 0), 'order_number': 0, 'direction': True},
            {'line_name': '1', 'stop_name': 'Hlavní nádraží', 'time': datetime.time(6, 30, 0), 'order_number': 0, 'direction': False},
            {'line_name': '1', 'stop_name': 'Malinovského náměstí', 'time': datetime.time(6, 10, 0), 'order_number': 1, 'direction': True},
            {'line_name': '1', 'stop_name': 'Malinovského náměstí', 'time': datetime.time(6, 40, 0), 'order_number': 1, 'direction': False},
            {'line_name': '1', 'stop_name': 'Moravské náměstí', 'time': datetime.time(6, 20, 0), 'order_number': 2, 'direction': True},
            {'line_name': '1', 'stop_name': 'Moravské náměstí', 'time': datetime.time(6, 50, 0), 'order_number': 2, 'direction': False},
            {'line_name': '1', 'stop_name': 'Antonínská', 'time': datetime.time(6, 30, 0), 'order_number': 3, 'direction': True},
            {'line_name': '1', 'stop_name': 'Antonínská', 'time': datetime.time(7, 0, 0), 'order_number': 3, 'direction': False},
            {'line_name': '1', 'stop_name': 'Komenského náměstí', 'time': datetime.time(6, 40, 0), 'order_number': 4, 'direction': True},
            {'line_name': '1', 'stop_name': 'Komenského náměstí', 'time': datetime.time(7, 10, 0), 'order_number': 4, 'direction': False},
            {'line_name': '1', 'stop_name': 'Sokolská', 'time': datetime.time(6, 50, 0), 'order_number': 5, 'direction': True},
            {'line_name': '1', 'stop_name': 'Sokolská', 'time': datetime.time(7, 20, 0), 'order_number': 5, 'direction': False},
            {'line_name': '1', 'stop_name': 'Česká', 'time': datetime.time(7, 0, 0), 'order_number': 6, 'direction': True},
            {'line_name': '1', 'stop_name': 'Česká', 'time': datetime.time(7, 30, 0), 'order_number': 6, 'direction': False},
            {'line_name': '1', 'stop_name': 'Kartouzská', 'time': datetime.time(7, 10, 0), 'order_number': 7, 'direction': True},
            {'line_name': '1', 'stop_name': 'Kartouzská', 'time': datetime.time(7, 40, 0), 'order_number': 7, 'direction': False},
            {'line_name': '1', 'stop_name': 'Šumavská', 'time': datetime.time(7, 20, 0), 'order_number': 8, 'direction': True},
            {'line_name': '1', 'stop_name': 'Šumavská', 'time': datetime.time(7, 50, 0), 'order_number': 8, 'direction': False},

            {'line_name': '2', 'stop_name': 'Moravské náměstí', 'time': datetime.time(6, 0, 0), 'order_number': 0, 'direction': True},
            {'line_name': '2', 'stop_name': 'Moravské náměstí', 'time': datetime.time(6, 30, 0), 'order_number': 0, 'direction': False},
            {'line_name': '2', 'stop_name': 'Kounicova', 'time': datetime.time(6, 10, 0), 'order_number': 1, 'direction': True},
            {'line_name': '2', 'stop_name': 'Kounicova', 'time': datetime.time(6, 40, 0), 'order_number': 1, 'direction': False},
            {'line_name': '2', 'stop_name': 'Kopečná', 'time': datetime.time(6, 20, 0), 'order_number': 2, 'direction': True},
            {'line_name': '2', 'stop_name': 'Kopečná', 'time': datetime.time(6, 50, 0), 'order_number': 2, 'direction': False},
            {'line_name': '2', 'stop_name': 'Hrnčířská', 'time': datetime.time(6, 30, 0), 'order_number': 3, 'direction': True},
            {'line_name': '2', 'stop_name': 'Hrnčířská', 'time': datetime.time(7, 0, 0), 'order_number': 3, 'direction': False},
            {'line_name': '2', 'stop_name': 'Mendlovo Náměstí', 'time': datetime.time(6, 40, 0), 'order_number': 4, 'direction': True},
            {'line_name': '2', 'stop_name': 'Mendlovo Náměstí', 'time': datetime.time(7, 10, 0), 'order_number': 4, 'direction': False},
            {'line_name': '2', 'stop_name': 'Kuldova', 'time': datetime.time(6, 50, 0), 'order_number': 5, 'direction': True},
            {'line_name': '2', 'stop_name': 'Kuldova', 'time': datetime.time(7, 20, 0), 'order_number': 5, 'direction': False},
            {'line_name': '2', 'stop_name': 'Kotlářská', 'time': datetime.time(7, 0, 0), 'order_number': 6, 'direction': True},
            {'line_name': '2', 'stop_name': 'Kotlářská', 'time': datetime.time(7, 30, 0), 'order_number': 6, 'direction': False},
            {'line_name': '2', 'stop_name': 'Vlhká', 'time': datetime.time(7, 10, 0), 'order_number': 7, 'direction': True},
            {'line_name': '2', 'stop_name': 'Vlhká', 'time': datetime.time(7, 40, 0), 'order_number': 7, 'direction': False},
            {'line_name': '2', 'stop_name': 'Masná', 'time': datetime.time(7, 20, 0), 'order_number': 8, 'direction': True},
            {'line_name': '2', 'stop_name': 'Masná', 'time': datetime.time(7, 50, 0), 'order_number': 8, 'direction': False},

            {'line_name': '3', 'stop_name': 'Komenského náměstí', 'time': datetime.time(6, 0, 0), 'order_number': 0, 'direction': True},
            {'line_name': '3', 'stop_name': 'Komenského náměstí', 'time': datetime.time(6, 30, 0), 'order_number': 0, 'direction': False},
            {'line_name': '3', 'stop_name': 'Vsetínská', 'time': datetime.time(6, 10, 0), 'order_number': 1, 'direction': True},
            {'line_name': '3', 'stop_name': 'Vsetínská', 'time': datetime.time(6, 40, 0), 'order_number': 1, 'direction': False},
            {'line_name': '3', 'stop_name': 'Kamenná', 'time': datetime.time(6, 20, 0), 'order_number': 2, 'direction': True},
            {'line_name': '3', 'stop_name': 'Kamenná', 'time': datetime.time(6, 50, 0), 'order_number': 2, 'direction': False},
            {'line_name': '3', 'stop_name': 'Křenová', 'time': datetime.time(6, 30, 0), 'order_number': 3, 'direction': True},
            {'line_name': '3', 'stop_name': 'Křenová', 'time': datetime.time(7, 0, 0), 'order_number': 3, 'direction': False},
            {'line_name': '3', 'stop_name': 'Úvoz', 'time': datetime.time(6, 40, 0), 'order_number': 4, 'direction': True},
            {'line_name': '3', 'stop_name': 'Úvoz', 'time': datetime.time(7, 10, 0), 'order_number': 4, 'direction': False},
            {'line_name': '3', 'stop_name': 'Husitská', 'time': datetime.time(6, 50, 0), 'order_number': 5, 'direction': True},
            {'line_name': '3', 'stop_name': 'Husitská', 'time': datetime.time(7, 20, 0), 'order_number': 5, 'direction': False},
            {'line_name': '3', 'stop_name': 'Náměstí Míru', 'time': datetime.time(7, 0, 0), 'order_number': 6, 'direction': True},
            {'line_name': '3', 'stop_name': 'Náměstí Míru', 'time': datetime.time(7, 30, 0), 'order_number': 6, 'direction': False},
            {'line_name': '3', 'stop_name': 'Česká', 'time': datetime.time(7, 10, 0), 'order_number': 7, 'direction': True},
            {'line_name': '3', 'stop_name': 'Česká', 'time': datetime.time(7, 40, 0), 'order_number': 7, 'direction': False},
            {'line_name': '3', 'stop_name': 'Kartouzská', 'time': datetime.time(7, 20, 0), 'order_number': 8, 'direction': True},
            {'line_name': '3', 'stop_name': 'Kartouzská', 'time': datetime.time(7, 50, 0), 'order_number': 8, 'direction': False},

            {'line_name': 'E46', 'stop_name': 'Česká', 'time': datetime.time(6, 0, 0), 'order_number': 0, 'direction': True},
            {'line_name': 'E46', 'stop_name': 'Česká', 'time': datetime.time(6, 30, 0), 'order_number': 0, 'direction': False},
            {'line_name': 'E46', 'stop_name': 'Sokolská', 'time': datetime.time(6, 10, 0), 'order_number': 1, 'direction': True},
            {'line_name': 'E46', 'stop_name': 'Sokolská', 'time': datetime.time(6, 40, 0), 'order_number': 1, 'direction': False},
            {'line_name': 'E46', 'stop_name': 'Komenského náměstí', 'time': datetime.time(6, 20, 0), 'order_number': 2, 'direction': True},
            {'line_name': 'E46', 'stop_name': 'Komenského náměstí', 'time': datetime.time(6, 50, 0), 'order_number': 2, 'direction': False},
            {'line_name': 'E46', 'stop_name': 'Antonínská', 'time': datetime.time(6, 30, 0), 'order_number': 3, 'direction': True},
            {'line_name': 'E46', 'stop_name': 'Antonínská', 'time': datetime.time(7, 0, 0), 'order_number': 3, 'direction': False},
            {'line_name': 'E46', 'stop_name': 'Moravské náměstí', 'time': datetime.time(6, 40, 0), 'order_number': 4, 'direction': True},
            {'line_name': 'E46', 'stop_name': 'Moravské náměstí', 'time': datetime.time(7, 10, 0), 'order_number': 4, 'direction': False},
            {'line_name': 'E46', 'stop_name': 'Malinovského náměstí', 'time': datetime.time(7, 0, 0), 'order_number': 5, 'direction': True},
            {'line_name': 'E46', 'stop_name': 'Malinovského náměstí', 'time': datetime.time(7, 30, 0), 'order_number': 5, 'direction': False},
            {'line_name': 'E46', 'stop_name': 'Hlavní nádraží', 'time': datetime.time(7, 20, 0), 'order_number': 6, 'direction': True},
            {'line_name': 'E46', 'stop_name': 'Hlavní nádraží', 'time': datetime.time(7, 50, 0), 'order_number': 6, 'direction': False},

            {'line_name': 'E48', 'stop_name': 'Masná', 'time': datetime.time(6, 0, 0), 'order_number': 0, 'direction': True},
            {'line_name': 'E48', 'stop_name': 'Masná', 'time': datetime.time(6, 30, 0), 'order_number': 0, 'direction': False},
            {'line_name': 'E48', 'stop_name': 'Vlhká', 'time': datetime.time(6, 10, 0), 'order_number': 1, 'direction': True},
            {'line_name': 'E48', 'stop_name': 'Vlhká', 'time': datetime.time(6, 40, 0), 'order_number': 1, 'direction': False},
            {'line_name': 'E48', 'stop_name': 'Kotlářská', 'time': datetime.time(6, 20, 0), 'order_number': 2, 'direction': True},
            {'line_name': 'E48', 'stop_name': 'Kotlářská', 'time': datetime.time(6, 50, 0), 'order_number': 2, 'direction': False},
            {'line_name': 'E48', 'stop_name': 'Kuldova', 'time': datetime.time(6, 30, 0), 'order_number': 3, 'direction': True},
            {'line_name': 'E48', 'stop_name': 'Kuldova', 'time': datetime.time(7, 0, 0), 'order_number': 3, 'direction': False},
            {'line_name': 'E48', 'stop_name': 'Mendlovo Náměstí', 'time': datetime.time(6, 40, 0), 'order_number': 4, 'direction': True},
            {'line_name': 'E48', 'stop_name': 'Mendlovo Náměstí', 'time': datetime.time(7, 10, 0), 'order_number': 4, 'direction': False},
            {'line_name': 'E48', 'stop_name': 'Hrnčířská', 'time': datetime.time(6, 50, 0), 'order_number': 5, 'direction': True},
            {'line_name': 'E48', 'stop_name': 'Hrnčířská', 'time': datetime.time(7, 20, 0), 'order_number': 5, 'direction': False},
            {'line_name': 'E48', 'stop_name': 'Kopečná', 'time': datetime.time(7, 0, 0), 'order_number': 6, 'direction': True},
            {'line_name': 'E48', 'stop_name': 'Kopečná', 'time': datetime.time(7, 30, 0), 'order_number': 6, 'direction': False},
            {'line_name': 'E48', 'stop_name': 'Kounicova', 'time': datetime.time(7, 10, 0), 'order_number': 7, 'direction': True},
            {'line_name': 'E48', 'stop_name': 'Kounicova', 'time': datetime.time(7, 40, 0), 'order_number': 7, 'direction': False},

            {'line_name': 'E50', 'stop_name': 'Náměstí Míru', 'time': datetime.time(6, 0, 0), 'order_number': 0, 'direction': True},
            {'line_name': 'E50', 'stop_name': 'Náměstí Míru', 'time': datetime.time(6, 30, 0), 'order_number': 0, 'direction': False},
            {'line_name': 'E50', 'stop_name': 'Husitská', 'time': datetime.time(6, 10, 0), 'order_number': 1, 'direction': True},
            {'line_name': 'E50', 'stop_name': 'Husitská', 'time': datetime.time(6, 40, 0), 'order_number': 1, 'direction': False},
            {'line_name': 'E50', 'stop_name': 'Úvoz', 'time': datetime.time(6, 20, 0), 'order_number': 2, 'direction': True},
            {'line_name': 'E50', 'stop_name': 'Úvoz', 'time': datetime.time(6, 50, 0), 'order_number': 2, 'direction': False},
            {'line_name': 'E50', 'stop_name': 'Křenová', 'time': datetime.time(6, 30, 0), 'order_number': 3, 'direction': True},
            {'line_name': 'E50', 'stop_name': 'Křenová', 'time': datetime.time(7, 0, 0), 'order_number': 3, 'direction': False},
            {'line_name': 'E50', 'stop_name': 'Kamenná', 'time': datetime.time(6, 40, 0), 'order_number': 4, 'direction': True},
            {'line_name': 'E50', 'stop_name': 'Kamenná', 'time': datetime.time(7, 10, 0), 'order_number': 4, 'direction': False},
            {'line_name': 'E50', 'stop_name': 'Vsetínská', 'time': datetime.time(7, 0, 0), 'order_number': 5, 'direction': True},
            {'line_name': 'E50', 'stop_name': 'Vsetínská', 'time': datetime.time(7, 30, 0), 'order_number': 5, 'direction': False},
            {'line_name': 'E50', 'stop_name': 'Komenského náměstí', 'time': datetime.time(7, 10, 0), 'order_number': 6, 'direction': True},
            {'line_name': 'E50', 'stop_name': 'Komenského náměstí', 'time': datetime.time(7, 40, 0), 'order_number': 6, 'direction': False},
            {'line_name': 'E50', 'stop_name': 'Antonínská', 'time': datetime.time(7, 20, 0), 'order_number': 7, 'direction': True},
            {'line_name': 'E50', 'stop_name': 'Antonínská', 'time': datetime.time(7, 50, 0), 'order_number': 7, 'direction': False},
            {'line_name': 'E50', 'stop_name': 'Moravské náměstí', 'time': datetime.time(7, 30, 0), 'order_number': 8, 'direction': True},
            {'line_name': 'E50', 'stop_name': 'Moravské náměstí', 'time': datetime.time(8, 0, 0), 'order_number': 8, 'direction': False},
        ]
    )

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('timestop')
    op.drop_table('ride')
    op.drop_table('malfunction')
    op.drop_table('maintenance')
    op.drop_table('departures')
    op.drop_table('vehicles')
    op.drop_table('users')
    op.drop_table('trafficline')
    op.drop_table('stop')
    # ### end Alembic commands ###
